#pragma once

#include "OpenSRX/ParamValues.hpp"

namespace OpenSRX {

/**
 * @brief Command numbers for parameter bank configuration (WB/RB commands).
 *
 * Used with the WB (write bank) and RB (read bank) commands in the format:
 *   WB,bm,n  (write)   RB,bm  (read)
 * where b = bank number (01–16), m = command number, n = setting value.
 */
enum class BankParam {
    // -- Bank name --
    BANK_NAME = 625,

    // -- Lighting --
    INTERNAL_LIGHTING_USE = 0,
    EXTERNAL_LIGHTING_USE = 4,
    INTERNAL_LIGHTING_TYPE = 10,

    // -- Scanning --
    EXPOSURE_TIME = 100,
    GAIN = 101,
    CONTRAST_ADJUSTMENT_METHOD = 108,

    // -- AI --
    AI_FILTER = 519,

    // -- Code settings --
    CONTRAST_THRESHOLD_CORRECTION = 506,

    // -- Filter settings --
    FILTER_1ST_TYPE = 200,
    FILTER_2ND_TYPE = 201,
    FILTER_3RD_TYPE = 202,
    FILTER_4TH_TYPE = 203,
    FILTER_1ST_COUNT = 210,
    FILTER_2ND_COUNT = 211,
    FILTER_3RD_COUNT = 212,
    FILTER_4TH_COUNT = 213,

    // -- Code type --
    CODE_TYPE = 300,
    OUTPUT_LENGTH_LIMITATION = 306,
    OUTPUT_DIRECTION = 307,
    OUTPUT_LENGTH = 308,
    OUTPUT_STARTING_INDEX = 309,
    ECI_OUTPUT = 310,

    // -- QR code --
    QR_LENGTH_LIMITATION_METHOD = 700,
    QR_LENGTH_LIMITATION_VALUE = 701,
    QR_MAX_READ_LENGTH = 321,
    QR_MIN_READ_LENGTH = 322,
    QR_VERSION_MODEL1 = 400,
    QR_VERSION_MODEL2_1_20 = 401,
    QR_VERSION_MODEL2_21_40 = 402,
    QR_VERSION_MICRO = 403,
    QR_GRID_CORRECTION = 500,

    // -- Data Matrix --
    DATAMATRIX_LENGTH_LIMITATION_METHOD = 702,
    DATAMATRIX_LENGTH_LIMITATION_VALUE = 703,
    DATAMATRIX_MAX_READ_LENGTH = 323,
    DATAMATRIX_MIN_READ_LENGTH = 324,
    DATAMATRIX_TARGET_SIZE = 410,
    DMRE_TARGET_SIZE = 820,

    // -- PDF417 --
    PDF417_LENGTH_LIMITATION_METHOD = 704,
    PDF417_LENGTH_LIMITATION_VALUE = 705,
    PDF417_READ_CODE_TYPE = 420,
    PDF417_MAX_READ_LENGTH = 325,
    PDF417_MIN_READ_LENGTH = 326,
    PDF417_DECODE_MATCHES = 658,

    // -- MaxiCode --
    MAXICODE_LENGTH_LIMITATION_METHOD = 734,
    MAXICODE_LENGTH_LIMITATION_VALUE = 735,
    MAXICODE_MAX_READ_LENGTH = 475,
    MAXICODE_MIN_READ_LENGTH = 476,

    // -- GS1 DataBar --
    GS1_DATABAR_LENGTH_LIMITATION_METHOD = 706,
    GS1_DATABAR_LENGTH_LIMITATION_VALUE = 707,
    GS1_DATABAR_MAX_READ_LENGTH = 327,
    GS1_DATABAR_MIN_READ_LENGTH = 328,
    GS1_DATABAR_DECODE_MATCHES = 659,
    GS1_DATABAR_RIGHT_SPACE_RATIO = 681,
    GS1_DATABAR_OMNIDIRECTIONAL = 390,
    GS1_DATABAR_STACKED = 391,
    GS1_DATABAR_LIMITED = 392,
    GS1_DATABAR_EXPANDED = 393,
    GS1_DATABAR_EXPANDED_STACKED = 394,
    GS1_DATABAR_EXPANDED_STACKED_ROWS_MIN = 395,
    GS1_DATABAR_EXPANDED_STACKED_ROWS_MAX = 396,

    // -- CODE 39 --
    CODE39_LENGTH_LIMITATION_METHOD = 708,
    CODE39_LENGTH_LIMITATION_VALUE = 709,
    CODE39_MAX_READ_LENGTH = 329,
    CODE39_MIN_READ_LENGTH = 330,
    CODE39_DECODE_MATCHES = 660,
    CODE39_QUIET_ZONE_RATIO = 682,
    CODE39_SEND_START_STOP = 375,
    CODE39_INSPECT_CHECK_DIGIT = 376,
    CODE39_SEND_CHECK_DIGIT = 377,
    CODE39_TRIOPTIC_READING = 378,
    CODE39_FULL_ASCII = 379,

    // -- ITF --
    ITF_LENGTH_LIMITATION_METHOD = 710,
    ITF_LENGTH_LIMITATION_VALUE = 711,
    ITF_MAX_READ_LENGTH = 331,
    ITF_MIN_READ_LENGTH = 332,
    ITF_DECODE_MATCHES = 661,
    ITF_QUIET_ZONE_RATIO = 683,
    ITF_INSPECT_CHECK_DIGIT = 385,
    ITF_SEND_CHECK_DIGIT = 386,

    // -- 2 of 5 --
    TWO_OF_5_LENGTH_LIMITATION_METHOD = 712,
    TWO_OF_5_LENGTH_LIMITATION_VALUE = 713,
    TWO_OF_5_MAX_READ_LENGTH = 333,
    TWO_OF_5_MIN_READ_LENGTH = 334,
    TWO_OF_5_DECODE_MATCHES = 662,
    TWO_OF_5_QUIET_ZONE_RATIO = 684,

    // -- NW-7 (CodaBar) --
    NW7_LENGTH_LIMITATION_METHOD = 714,
    NW7_LENGTH_LIMITATION_VALUE = 715,
    NW7_MAX_READ_LENGTH = 335,
    NW7_MIN_READ_LENGTH = 336,
    NW7_DECODE_MATCHES = 663,
    NW7_QUIET_ZONE_RATIO = 685,
    NW7_SEND_START_STOP = 380,
    NW7_START_STOP_LETTER_TYPE = 381,
    NW7_INSPECT_CHECK_DIGIT = 382,
    NW7_SEND_CHECK_DIGIT = 383,
    NW7_CHECK_DIGIT_TYPE = 384,

    // -- JAN/EAN/UPC --
    JAN_EAN_UPC_DECODE_MATCHES = 664,
    JAN_EAN_UPC_QUIET_ZONE_RATIO = 686,
    UPC_E_READING = 350,
    EAN_JAN_8_READING = 351,
    EAN_JAN_13_READING = 352,
    UPC_A_OUTPUT = 353,
    UPC_E_NUMBER_SYSTEM = 354,
    SUPPLEMENTAL_2_DIGIT = 355,
    SUPPLEMENTAL_5_DIGIT = 356,
    IGNORE_UPC_WITHOUT_SUPPLEMENTAL = 357,
    GTIN_14_DIGIT_OUTPUT = 358,

    // -- CODE 128 --
    CODE128_LENGTH_LIMITATION_METHOD = 716,
    CODE128_LENGTH_LIMITATION_VALUE = 717,
    CODE128_MAX_READ_LENGTH = 337,
    CODE128_MIN_READ_LENGTH = 338,
    CODE128_DECODE_MATCHES = 665,
    CODE128_QUIET_ZONE_RATIO = 687,
    CODE128_GS1_128 = 366,

    // -- COOP 2 of 5 --
    COOP_2OF5_LENGTH_LIMITATION_METHOD = 718,
    COOP_2OF5_LENGTH_LIMITATION_VALUE = 719,
    COOP_2OF5_MAX_READ_LENGTH = 339,
    COOP_2OF5_MIN_READ_LENGTH = 340,
    COOP_2OF5_DECODE_MATCHES = 666,
    COOP_2OF5_QUIET_ZONE_RATIO = 688,

    // -- CODE 93 --
    CODE93_LENGTH_LIMITATION_METHOD = 720,
    CODE93_LENGTH_LIMITATION_VALUE = 721,
    CODE93_MAX_READ_LENGTH = 341,
    CODE93_MIN_READ_LENGTH = 342,
    CODE93_DECODE_MATCHES = 667,
    CODE93_QUIET_ZONE_RATIO = 689,

    // -- GS1 Composite CC-A/B (GS1 DataBar) --
    GS1_COMPOSITE_DATABAR_LENGTH_LIMITATION_METHOD = 722,
    GS1_COMPOSITE_DATABAR_LENGTH_LIMITATION_VALUE = 723,
    GS1_COMPOSITE_DATABAR_MAX_READ_LENGTH = 343,
    GS1_COMPOSITE_DATABAR_MIN_READ_LENGTH = 344,

    // -- GS1 Composite CC-A/B (EAN/UPC) --
    GS1_COMPOSITE_EAN_UPC_LENGTH_LIMITATION_METHOD = 724,
    GS1_COMPOSITE_EAN_UPC_LENGTH_LIMITATION_VALUE = 725,
    GS1_COMPOSITE_EAN_UPC_MAX_READ_LENGTH = 345,
    GS1_COMPOSITE_EAN_UPC_MIN_READ_LENGTH = 346,

    // -- GS1 Composite CC-A/B/C (GS1-128) --
    GS1_COMPOSITE_GS1_128_LENGTH_LIMITATION_METHOD = 726,
    GS1_COMPOSITE_GS1_128_LENGTH_LIMITATION_VALUE = 727,
    GS1_COMPOSITE_GS1_128_MAX_READ_LENGTH = 347,
    GS1_COMPOSITE_GS1_128_MIN_READ_LENGTH = 348,
    GS1_COMPOSITE_GS1_128_CC_C_READING = 437,

    // -- Postal --
    POSTAL_LENGTH_LIMITATION_METHOD = 728,
    POSTAL_LENGTH_LIMITATION_VALUE = 729,
    POSTAL_MAX_READ_LENGTH = 447,
    POSTAL_MIN_READ_LENGTH = 448,
    POSTAL_JAPAN_READING = 446,
    POSTAL_INTELLIGENT_MAIL = 443,

    // -- Pharmacode --
    PHARMACODE_MAX_BARS = 440,
    PHARMACODE_MIN_BARS = 441,
    PHARMACODE_DECODE_MATCHES = 669,
    PHARMACODE_QUIET_ZONE_RATIO = 690,
    PHARMACODE_READ_DIRECTION = 530,
    PHARMACODE_BINARY_OUTPUT = 442,

    // -- DotCode --
    DOTCODE_LENGTH_LIMITATION_METHOD = 730,
    DOTCODE_LENGTH_LIMITATION_VALUE = 731,
    DOTCODE_MAX_READ_LENGTH = 460,
    DOTCODE_MIN_READ_LENGTH = 461,
    DOTCODE_MAX_ROWS = 462,
    DOTCODE_MIN_ROWS = 463,
    DOTCODE_MAX_COLUMNS = 464,
    DOTCODE_MIN_COLUMNS = 465,

    // -- Aztec Code --
    AZTEC_LENGTH_LIMITATION_METHOD = 732,
    AZTEC_LENGTH_LIMITATION_VALUE = 733,
    AZTEC_MAX_READ_LENGTH = 470,
    AZTEC_MIN_READ_LENGTH = 471,

    // -- Reading operation settings --
    ALTERNATE = 600,
    INTERNAL_BANK_RETRY_COUNT = 601,
    DECODE_TIMEOUT_DURATION = 602,
    REGION_NUMBER = 604,
    INVERSE = 605,
    REVERSE = 606,
    BASE_TILT_ANGLE = 607,
    TILT_ANGLE_RANGE = 608,
    CODE_ORIENTATION_1D = 613,
};

}  // namespace OpenSRX
